// Generating a CRE workflow around a creator's strategy, then driving the
// `cre` CLI over it.
//
// `cre workflow simulate` fires a cron trigger exactly once and exits: the
// schedule string is validated but not honoured, and `--listen` is rejected for
// cron triggers. So there is no loop to start here — the platform scheduler owns
// the interval and calls simulateWorkflow() once per tick.

import { spawn } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join, relative } from 'node:path'
import ts from 'typescript'
import type { TickDecision } from '../../../shared/strategy-contract'
import type { SanityCheck } from '../../../shared/types'
import { failed, passed } from './checks'
import {
	chainlinkDir,
	CONTRACT_FILE_NAME,
	CONTRACT_SPECIFIER,
	readContractSource,
	STRATEGY_FILE_NAME,
	strategyRunnerDir,
	toolkitDir,
} from './paths'

/** Marker the generated workflow prints its decision behind. */
export const DECISION_PREFIX = 'attesta-decision:'

const DEFAULT_TARGET = 'staging-settings'
const DEFAULT_SCHEDULE = '0 */1 * * * *'
const DEFAULT_ORACLE_URL = 'http://127.0.0.1:8787/api/oracle/prices'
const DEFAULT_SECRET_NAMESPACE = 'main'
const DEFAULT_TIMEOUT_MS = 10 * 60 * 1000

export interface WorkflowOptions {
	/** Directory name for the generated workflow. Defaults to the ticker. */
	name?: string
	/** Where to generate. Defaults to <toolkit>/.workflows/<name>. */
	outDir?: string
	/** Endpoint the enclave GETs prices from, per tick. */
	oracleUrl?: string
	/** Written into config; validated by the simulator, honoured only when deployed. */
	schedule?: string
	secretNamespace?: string
	/** Maps a strategy's secret id onto the Vault id actually provisioned. */
	secretAliases?: Record<string, string>
	/** USDC under management for this tick, 6dp integer string. */
	totalAssets?: string
	currentWeightsBps?: Record<string, number>
	target?: string
	/** Path to the env file, relative to the chainlink project root. */
	envFile?: string
	timeoutMs?: number
}

export interface GeneratedWorkflow {
	/** Absolute path of the generated workflow directory. */
	dir: string
	/** Same path relative to the chainlink project root, as the CLI wants it. */
	relativeDir: string
	projectRoot: string
	name: string
	files: string[]
}

// ─── Source rewriting ───────────────────────────────────────────────────────

/**
 * Rewrites the contract's bare specifier to a relative one for the generated
 * directory. Done over the AST rather than by string replacement so a specifier
 * inside a comment or a string literal is left alone.
 */
export function rewriteContractImports(source: string, target: string): string {
	const sourceFile = ts.createSourceFile(
		STRATEGY_FILE_NAME,
		source,
		ts.ScriptTarget.ESNext,
		true,
		ts.ScriptKind.TS,
	)

	const edits: Array<{ start: number; end: number; text: string }> = []
	const visit = (node: ts.Node): void => {
		if (
			(ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
			node.moduleSpecifier &&
			ts.isStringLiteralLike(node.moduleSpecifier) &&
			node.moduleSpecifier.text === CONTRACT_SPECIFIER
		) {
			edits.push({
				start: node.moduleSpecifier.getStart(sourceFile),
				end: node.moduleSpecifier.getEnd(),
				text: JSON.stringify(target),
			})
		}
		ts.forEachChild(node, visit)
	}
	visit(sourceFile)

	let output = source
	for (const edit of edits.sort((a, b) => b.start - a.start)) {
		output = output.slice(0, edit.start) + edit.text + output.slice(edit.end)
	}
	return output
}

const slug = (value: string): string =>
	value
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '') || 'strategy'

// ─── Generation ─────────────────────────────────────────────────────────────

const workflowYaml = (name: string, secretsPath: string): string => `# Generated by @attesta/strategy-toolkit. Regenerated on every build.
staging-settings:
  user-workflow:
    workflow-name: "${name}"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "${secretsPath}"

production-settings:
  user-workflow:
    workflow-name: "${name}"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "${secretsPath}"
`

const workflowPackageJson = (name: string): string =>
	`${JSON.stringify(
		{
			name: `attesta-${name}`,
			version: '1.0.0',
			main: 'dist/main.js',
			private: true,
			license: 'UNLICENSED',
			scripts: { typecheck: 'tsc --noEmit' },
			dependencies: {
				'@chainlink/cre-sdk': '1.18.0',
				viem: '2.34.0',
				zod: '3.25.76',
			},
			devDependencies: { typescript: '5.9.3' },
		},
		null,
		2,
	)}\n`

const WORKFLOW_TSCONFIG = `${JSON.stringify(
	{
		compilerOptions: {
			target: 'esnext',
			module: 'ESNext',
			moduleResolution: 'bundler',
			lib: ['ESNext'],
			outDir: './dist',
			strict: true,
			esModuleInterop: true,
			skipLibCheck: true,
			forceConsistentCasingInFileNames: true,
			types: [],
		},
		include: ['main.ts'],
	},
	null,
	2,
)}\n`

function buildConfig(options: WorkflowOptions): string {
	return `${JSON.stringify(
		{
			schedule: options.schedule ?? DEFAULT_SCHEDULE,
			oracleUrl: options.oracleUrl ?? DEFAULT_ORACLE_URL,
			secretNamespace: options.secretNamespace ?? DEFAULT_SECRET_NAMESPACE,
			secretAliases: options.secretAliases ?? {},
			totalAssets: options.totalAssets ?? '1000000000',
			currentWeightsBps: options.currentWeightsBps ?? {},
		},
		null,
		2,
	)}\n`
}

/**
 * Writes a complete CRE workflow directory for `source`. node_modules is
 * symlinked to the reference runner's rather than installed: the dependency set
 * is pinned and identical, and a per-strategy install would put an npm fetch in
 * the middle of the submission pipeline.
 */
export async function generateWorkflow(
	source: string,
	options: WorkflowOptions = {},
): Promise<GeneratedWorkflow> {
	const projectRoot = chainlinkDir()
	const name = slug(options.name ?? 'strategy')
	const dir = options.outDir ?? join(toolkitDir(), '.workflows', name)

	await rm(dir, { recursive: true, force: true })
	await mkdir(dir, { recursive: true })

	const contractModule = `./${CONTRACT_FILE_NAME.replace(/\.ts$/, '')}`
	const runnerSrc = join(toolkitDir(), 'src', 'cre-workflow')
	const secretsPath = relative(dir, join(projectRoot, 'secrets.yaml'))
	const config = buildConfig(options)

	const files: Array<[string, string]> = [
		[STRATEGY_FILE_NAME, rewriteContractImports(source, contractModule)],
		[CONTRACT_FILE_NAME, readContractSource()],
		['workflow.ts', await readFile(join(runnerSrc, 'workflow.ts'), 'utf8')],
		['main.ts', await readFile(join(runnerSrc, 'main.ts'), 'utf8')],
		['config.staging.json', config],
		['config.production.json', config],
		['workflow.yaml', workflowYaml(`attesta-${name}`, secretsPath)],
		['package.json', workflowPackageJson(name)],
		['tsconfig.json', WORKFLOW_TSCONFIG],
	]

	await Promise.all(files.map(([file, content]) => writeFile(join(dir, file), content, 'utf8')))

	const runnerModules = join(strategyRunnerDir(), 'node_modules')
	if (existsSync(runnerModules)) {
		await symlink(relative(dir, runnerModules), join(dir, 'node_modules'), 'dir')
	}

	return {
		dir,
		relativeDir: relative(projectRoot, dir),
		projectRoot,
		name,
		files: files.map(([file]) => file),
	}
}

// ─── Driving the CLI ────────────────────────────────────────────────────────

export interface CreRunResult {
	ok: boolean
	exitCode: number | null
	command: string
	stdout: string
	stderr: string
	durationMs: number
}

export interface CreBuildResult extends CreRunResult {
	workflow: GeneratedWorkflow
	/** sha256 of the compiled WASM — the strategy's permanent identity. */
	binaryHash: string | null
	configHash: string | null
	wasmPath: string
}

export interface CreSimulateResult extends CreBuildResult {
	/** The decision the strategy returned from inside the simulated enclave. */
	decision: TickDecision | null
	/** Every `[USER LOG]` line the enclave emitted, in order. */
	enclaveLogs: string[]
}

/** Resolves the `cre` binary: CRE_BIN, then PATH, then the default install. */
export function creBinary(): string {
	const fromEnv = process.env.CRE_BIN
	if (fromEnv && existsSync(fromEnv)) return fromEnv

	const installed = join(homedir(), '.cre', 'bin', 'cre')
	if (existsSync(installed)) return installed

	// Left to PATH resolution; spawn reports ENOENT clearly if it is not there.
	return 'cre'
}

function runCre(args: string[], cwd: string, timeoutMs: number): Promise<CreRunResult> {
	const binary = creBinary()
	const command = `${binary} ${args.join(' ')}`
	const startedAt = Date.now()

	return new Promise((resolve) => {
		const child = spawn(binary, args, { cwd, env: process.env })
		let stdout = ''
		let stderr = ''
		let timedOut = false

		const timer = setTimeout(() => {
			timedOut = true
			child.kill('SIGKILL')
		}, timeoutMs)

		child.stdout.on('data', (chunk: Buffer) => {
			stdout += chunk.toString()
		})
		child.stderr.on('data', (chunk: Buffer) => {
			stderr += chunk.toString()
		})

		const finish = (exitCode: number | null): void => {
			clearTimeout(timer)
			resolve({
				ok: exitCode === 0 && !timedOut,
				exitCode,
				command,
				stdout,
				stderr: timedOut ? `${stderr}\ntimed out after ${timeoutMs}ms` : stderr,
				durationMs: Date.now() - startedAt,
			})
		}

		child.on('error', (error) => {
			clearTimeout(timer)
			resolve({
				ok: false,
				exitCode: null,
				command,
				stdout,
				stderr: `${stderr}\ncould not run ${binary}: ${error.message}`,
				durationMs: Date.now() - startedAt,
			})
		})
		child.on('close', finish)
	})
}

const HASH_PATTERNS = {
	binaryHash: /Binary hash:\s*(?:0x)?([0-9a-f]{64})/i,
	configHash: /Config hash:\s*(?:0x)?([0-9a-f]{64})/i,
} as const

const matchHash = (output: string, pattern: RegExp): string | null => pattern.exec(output)?.[1] ?? null

function cliArgs(
	verb: 'build' | 'simulate',
	workflow: GeneratedWorkflow,
	options: WorkflowOptions,
): string[] {
	return [
		'workflow',
		verb,
		workflow.relativeDir,
		'--target',
		options.target ?? DEFAULT_TARGET,
		'-e',
		options.envFile ?? '.env',
	]
}

/** `cre workflow build` over a freshly generated directory. */
export async function buildWorkflow(
	source: string,
	options: WorkflowOptions = {},
): Promise<CreBuildResult> {
	const workflow = await generateWorkflow(source, options)
	const run = await runCre(
		cliArgs('build', workflow, options),
		workflow.projectRoot,
		options.timeoutMs ?? DEFAULT_TIMEOUT_MS,
	)
	const output = `${run.stdout}\n${run.stderr}`

	return {
		...run,
		workflow,
		binaryHash: matchHash(output, HASH_PATTERNS.binaryHash),
		configHash: matchHash(output, HASH_PATTERNS.configHash),
		wasmPath: join(workflow.dir, 'binary.wasm'),
	}
}

/**
 * `cre workflow simulate` over a freshly generated directory. Fires the cron
 * trigger once, then exits — call it again for the next tick.
 */
export async function simulateWorkflow(
	source: string,
	options: WorkflowOptions = {},
): Promise<CreSimulateResult> {
	const workflow = await generateWorkflow(source, options)
	const run = await runCre(
		cliArgs('simulate', workflow, options),
		workflow.projectRoot,
		options.timeoutMs ?? DEFAULT_TIMEOUT_MS,
	)
	const output = `${run.stdout}\n${run.stderr}`
	const decision = extractDecision(output)

	return {
		...run,
		// A simulation that produces no parseable decision has not done its job,
		// however cleanly the CLI exited.
		ok: run.ok && decision !== null,
		workflow,
		binaryHash: matchHash(output, HASH_PATTERNS.binaryHash),
		configHash: matchHash(output, HASH_PATTERNS.configHash),
		wasmPath: join(workflow.dir, 'binary.wasm'),
		decision,
		enclaveLogs: extractEnclaveLogs(output),
	}
}

// ─── Output parsing ─────────────────────────────────────────────────────────

const ACTIONS = new Set(['HOLD', 'REBALANCE', 'ENTER', 'EXIT'])

function asDecision(text: string): TickDecision | null {
	let parsed: unknown
	try {
		parsed = JSON.parse(text)
	} catch {
		return null
	}
	if (typeof parsed !== 'object' || parsed === null) return null

	const candidate = parsed as Partial<TickDecision>
	if (typeof candidate.action !== 'string' || !ACTIONS.has(candidate.action)) return null
	if (typeof candidate.reason !== 'string') return null
	if (typeof candidate.targetWeightsBps !== 'object' || candidate.targetWeightsBps === null) {
		return null
	}
	return candidate as TickDecision
}

/** Reads the JSON string literal that starts at the first quote after `from`. */
function readJsonStringLiteral(output: string, from: number): string | null {
	const start = output.indexOf('"', from)
	if (start === -1) return null

	for (let index = start + 1; index < output.length; index++) {
		const char = output[index]
		if (char === '\\') {
			index++
			continue
		}
		if (char === '"') {
			try {
				return JSON.parse(output.slice(start, index + 1)) as string
			} catch {
				return null
			}
		}
		if (char === '\n') return null
	}
	return null
}

/**
 * Lifts the decision out of simulator output. The `[USER LOG]` line carries it
 * verbatim; the returned value is JSON-escaped by the CLI, so that is the
 * fallback rather than the primary.
 */
export function extractDecision(output: string): TickDecision | null {
	for (const line of output.split('\n')) {
		const index = line.indexOf(DECISION_PREFIX)
		if (index === -1) continue
		const decision = asDecision(line.slice(index + DECISION_PREFIX.length).trim())
		if (decision) return decision
	}

	const resultIndex = output.indexOf('Workflow Simulation Result:')
	if (resultIndex !== -1) {
		const literal = readJsonStringLiteral(output, resultIndex)
		if (literal !== null) {
			const index = literal.indexOf(DECISION_PREFIX)
			if (index !== -1) return asDecision(literal.slice(index + DECISION_PREFIX.length).trim())
		}
	}

	return null
}

export function extractEnclaveLogs(output: string): string[] {
	const logs: string[] = []
	for (const line of output.split('\n')) {
		const index = line.indexOf('[USER LOG]')
		if (index !== -1) logs.push(line.slice(index + '[USER LOG]'.length).trim())
	}
	return logs
}

// ─── Pipeline checks ────────────────────────────────────────────────────────

const tail = (output: string, lines = 6): string =>
	output
		.split('\n')
		.map((line) => line.trim())
		.filter((line) => line.length > 0)
		.slice(-lines)
		.join(' | ')

export function creBuildCheck(result: CreBuildResult): SanityCheck {
	if (!result.ok) {
		return failed('cre-build', tail(`${result.stdout}\n${result.stderr}`))
	}
	if (!result.binaryHash) {
		return failed('cre-build', 'build succeeded but no binary hash appeared in the output')
	}
	return passed('cre-build', `binary hash ${result.binaryHash}`)
}

export function creSimulateCheck(result: CreSimulateResult): SanityCheck {
	if (!result.decision) {
		return failed(
			'cre-simulate',
			result.exitCode === 0
				? 'simulation finished without returning a parseable decision'
				: tail(`${result.stdout}\n${result.stderr}`),
		)
	}
	const weights = Object.entries(result.decision.targetWeightsBps)
		.map(([symbol, bps]) => `${symbol} ${bps}bps`)
		.join(', ')
	return passed('cre-simulate', `${result.decision.action}${weights ? ` -> ${weights}` : ''}`)
}
