// Emits src/chain/abis.ts from the Foundry artifacts in contracts/out.
//
// Hand-copied ABIs drift the moment a contract gains an argument, and a drifted ABI
// fails as a silent decode rather than a compile error, so the file is generated from
// whatever solc last produced and checked in alongside it.
//
// Run with `npm run chain:abis` after any change under contracts/src.

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { BACKEND_ROOT } from '../lib/paths.js'

const REPO_ROOT = path.resolve(BACKEND_ROOT, '..')
const CONTRACTS_DIR = path.join(REPO_ROOT, 'contracts')
const ARTIFACTS_DIR = path.join(CONTRACTS_DIR, 'out')
const TARGET = path.join(BACKEND_ROOT, 'src', 'chain', 'abis.ts')

interface Target {
	contract: string
	abiName: string
	bytecodeName: string
}

const TARGETS: Target[] = [
	{ contract: 'MockUSDC', abiName: 'mockUsdcAbi', bytecodeName: 'mockUsdcBytecode' },
	{ contract: 'StrategyVault', abiName: 'strategyVaultAbi', bytecodeName: 'strategyVaultBytecode' },
	{
		contract: 'StrategyRegistry',
		abiName: 'strategyRegistryAbi',
		bytecodeName: 'strategyRegistryBytecode',
	},
]

interface Artifact {
	abi: unknown[]
	bytecode: { object: string }
}

function artifactPath(contract: string): string {
	return path.join(ARTIFACTS_DIR, `${contract}.sol`, `${contract}.json`)
}

/** Artefacts are gitignored build output, so a clean checkout has to compile first. */
function ensureArtifacts(): void {
	const missing = TARGETS.filter((target) => !existsSync(artifactPath(target.contract)))
	if (missing.length === 0) return

	console.info(`compiling contracts — missing artifacts: ${missing.map((t) => t.contract).join(', ')}`)
	try {
		execFileSync('forge', ['build'], { cwd: CONTRACTS_DIR, stdio: 'inherit' })
	} catch (error) {
		console.error('forge build failed', { contractsDir: CONTRACTS_DIR, error })
		throw error
	}

	const stillMissing = TARGETS.filter((target) => !existsSync(artifactPath(target.contract)))
	if (stillMissing.length > 0) {
		throw new Error(
			`forge build produced no artifact for: ${stillMissing.map((t) => t.contract).join(', ')}`,
		)
	}
}

function readArtifact(contract: string): Artifact {
	const file = artifactPath(contract)
	try {
		const parsed = JSON.parse(readFileSync(file, 'utf8')) as Artifact
		if (!Array.isArray(parsed.abi)) throw new Error('artifact has no abi array')
		if (typeof parsed.bytecode?.object !== 'string') throw new Error('artifact has no bytecode')
		return parsed
	} catch (error) {
		console.error('could not read a contract artifact', { file, error })
		throw error
	}
}

/** JSON indented with tabs so the emitted file matches the repo's style. */
function literal(value: unknown): string {
	return JSON.stringify(value, null, '\t').split('\n').join('\n')
}

function render(): string {
	const parts: string[] = [
		'// GENERATED by src/chain/generate-abis.ts — do not edit.',
		'//',
		'// Source: contracts/out/<Contract>.sol/<Contract>.json (forge build).',
		'// Regenerate with `npm run chain:abis`.',
		'',
		"import type { Hex } from 'viem'",
		'',
	]

	for (const target of TARGETS) {
		const artifact = readArtifact(target.contract)
		const bytecode = artifact.bytecode.object.startsWith('0x')
			? artifact.bytecode.object
			: `0x${artifact.bytecode.object}`
		parts.push(`export const ${target.abiName} = ${literal(artifact.abi)} as const`)
		parts.push('')
		parts.push(`export const ${target.bytecodeName}: Hex = '${bytecode}'`)
		parts.push('')
	}

	return `${parts.join('\n').trimEnd()}\n`
}

ensureArtifacts()
const source = render()
writeFileSync(TARGET, source, 'utf8')
console.info(`wrote ${TARGET} (${source.length} bytes, ${TARGETS.length} contracts)`)
